apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-cluster-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      selectPolicy: Min
      policies:
        - periodSeconds: 60
          type: pods
          value: 1
