## Examples

### Using ARG in a Dockerfile
# Define build-time argument
ARG VERSION=1.0

# Use the build-time argument
FROM alpine:$VERSION

# Install curl with the specific version
RUN apk add --no-cache curl


# Build Command:
# docker build --build-arg VERSION=3.14 -t alpine-curl:3.14 .

