apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    group: my-lable
spec:
  selector:
    app: my-app-node-1
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 80
  type: LoadBalancer